// import type { Metadata } from "next";
// import "./globals.css";
// import Header from "@/components/Header";
// import { Footer } from "@/components/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="flex flex-col min-h-screen">
//         <div className="w-full fixed top-0 left-0 right-0 bg-white shadow-md z-50">
//           <div className="max-w-screen-xl mx-auto w-full">
//             <Header />
//           </div>
//         </div>

//         <main className="flex-1 p-4">
//           <div className="mx-auto w-full">
//               {children}
//           </div>
//         </main>

//         <footer className="w-full px-4 bg-background shadow-inner">
//           <div className="max-w-screen-xl mx-auto w-full">
//             <Footer />
//           </div>
//         </footer>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/Footer";
import LayoutClient from "./layout-client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <LayoutClient>
          {children}
        </LayoutClient>
        <footer className="w-full px-4 bg-background shadow-inner">
          <div className="max-w-screen-xl mx-auto w-full">
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}